# Generated by Django 5.0.2 on 2024-07-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(default=True, upload_to='img'),
        ),
    ]
