# Generated by Django 5.0.2 on 2024-07-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_image',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FilePathField(default=True, path='/img'),
        ),
    ]
